# FROM python:3.11.9

# WORKDIR /app

# # Copy files
# COPY . /app
# COPY requirements.txt /app/requirements.txt

# # Install dependencies
# RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

# EXPOSE 5000

# CMD ["python", "app.py"]

FROM python:3.11.9

# Set the working directory
WORKDIR /app

# Install OS dependencies for OpenCV
RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

# Copy application files (except DP folder if needed)
COPY . /app

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port
EXPOSE 5000

# Run the app
CMD ["python", "app.py"]
